"""cria relacao entre usuario e problema

Revision ID: 03d1ab6351f6
Revises: aa89827ad5f1
Create Date: 2024-01-23 17:21:06.252600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d1ab6351f6'
down_revision = 'aa89827ad5f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problemas', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('usuario_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_problemas_user", 'users', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problemas', schema=None) as batch_op:
        batch_op.drop_constraint("fk_problemas_user", type_='foreignkey')
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###
