"""adiciona coluna veredito em resposta

Revision ID: 0b16dad5aa50
Revises: c11b14d87ece
Create Date: 2024-03-02 17:34:39.906613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b16dad5aa50'
down_revision = 'c11b14d87ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema_respostas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('veredito', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema_respostas', schema=None) as batch_op:
        batch_op.drop_column('veredito')

    # ### end Alembic commands ###
