"""cria coluna de imagem em user

Revision ID: 0b76d8569b3a
Revises: eda77c342fdd
Create Date: 2024-03-17 11:23:17.697462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b76d8569b3a'
down_revision = 'eda77c342fdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caminho_imagem', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('caminho_imagem')

    # ### end Alembic commands ###
