"""Adiciona coluna de entrada de teste gerado

Revision ID: 2505e26d5c5f
Revises: d9affcc0a6fd
Create Date: 2024-08-24 22:44:29.293231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2505e26d5c5f'
down_revision = 'd9affcc0a6fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema_testes', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('entrada_gerado', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema_testes', schema=None) as batch_op:
        batch_op.drop_column('entrada_gerado')

    # ### end Alembic commands ###
