"""cria coluna saida usuario em resposta

Revision ID: 29aa2b54b068
Revises: 61e22bb179de
Create Date: 2024-03-07 21:16:27.227750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29aa2b54b068'
down_revision = '61e22bb179de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema_respostas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saida_usuario', sa.ARRAY(sa.String()), nullable=False))

    with op.batch_alter_table('problemas', schema=None) as batch_op:
        batch_op.create_foreign_key('problemas_verificador_id_fkey', 'verificadores', ['verificador_id'], ['id'], ondelete='SET NULL', use_alter=True)
        batch_op.create_foreign_key('problemas_validador_id_fkey', 'validadores', ['validador_id'], ['id'], ondelete='SET NULL', use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problemas', schema=None) as batch_op:
        batch_op.drop_constraint('problemas_validador_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('problemas_verificador_id_fkey', type_='foreignkey')

    with op.batch_alter_table('problema_respostas', schema=None) as batch_op:
        batch_op.drop_column('saida_usuario')

    # ### end Alembic commands ###
