"""altera tipo da coluna numero na tabela ProblemaTeste

Revision ID: 3229038106eb
Revises: f5512a600333
Create Date: 2024-02-09 01:25:56.038528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3229038106eb'
down_revision = 'f5512a600333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema_testes', schema=None) as batch_op:
        batch_op.alter_column('numero',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema_testes', schema=None) as batch_op:
        batch_op.alter_column('numero',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###
