"""inclui delete cascade entre problema e declaracao

Revision ID: 5534a923cf14
Revises: 6b43e7f72711
Create Date: 2024-03-30 14:26:29.274205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5534a923cf14'
down_revision = '6b43e7f72711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('declaracoes', schema=None) as batch_op:
        batch_op.drop_constraint('declaracoes_problema_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('declaracoes_problema_id_fkey', 'problemas', ['problema_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('declaracoes', schema=None) as batch_op:
        batch_op.drop_constraint('declaracoes_problema_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('declaracoes_problema_id_fkey', 'problemas', ['problema_id'], ['id'])

    # ### end Alembic commands ###
