"""insere coluna de data criacao em user

Revision ID: 5729be25b9d2
Revises: abb9072e627d
Create Date: 2024-02-16 17:12:52.198787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5729be25b9d2'
down_revision = 'abb9072e627d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_em', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('criado_em')

    # ### end Alembic commands ###
