"""aumenta tamanho de entrada de teste de problema

Revision ID: 5bffb763397b
Revises: e457c69065c4
Create Date: 2024-03-07 22:54:58.890389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bffb763397b'
down_revision = 'e457c69065c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema_testes', schema=None) as batch_op:
        batch_op.alter_column('entrada',
               existing_type=sa.VARCHAR(length=250000),
               type_=sa.String(length=1000000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema_testes', schema=None) as batch_op:
        batch_op.alter_column('entrada',
               existing_type=sa.String(length=1000000),
               type_=sa.VARCHAR(length=250000),
               existing_nullable=False)

    # ### end Alembic commands ###
