"""insere delete em cascata em verificadorTeste ao excluir verificador

Revision ID: 71a76b3153e7
Revises: 9b2c9985c469
Create Date: 2024-02-13 02:55:49.285525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71a76b3153e7'
down_revision = '9b2c9985c469'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verificador_testes', schema=None) as batch_op:
        batch_op.drop_constraint('verificador_testes_verificador_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('verificador_testes_verificador_id_fkey', 'verificadores', ['verificador_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verificador_testes', schema=None) as batch_op:
        batch_op.drop_constraint('verificador_testes_verificador_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('verificador_testes_verificador_id_fkey', 'verificadores', ['verificador_id'], ['id'])

    # ### end Alembic commands ###
