"""cria coluna veredito em validadorTeste

Revision ID: 766346bd7212
Revises: fe364ec5c283
Create Date: 2024-01-18 17:27:31.025066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766346bd7212'
down_revision = 'fe364ec5c283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('validador_testes', sa.Column('veredito', sa.Enum('VALID', 'INVALID', name='vereditovalidadortesteenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('validador_testes', 'veredito')
    # ### end Alembic commands ###
