"""cria models

Revision ID: 84905412ecb2
Revises: 
Create Date: 2024-01-14 13:29:43.570080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84905412ecb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problemas',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('nome', sa.String(length=64), nullable=False),
                    sa.Column('nome_arquivo_entrada', sa.String(
                        length=64), nullable=False),
                    sa.Column('nome_arquivo_saida', sa.String(
                        length=64), nullable=False),
                    sa.Column('tempo_limite', sa.Integer(), nullable=False),
                    sa.Column('memoria_limite', sa.Integer(), nullable=False),
                    sa.Column('verificador_id', sa.Integer(), nullable=True),
                    sa.Column('validador_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['validador_id'], ['validadores.id'], use_alter=True),
                    sa.ForeignKeyConstraint(['verificador_id'], [
                        'verificadores.id'], use_alter=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('validador_id'),
                    sa.UniqueConstraint('verificador_id')
                    )
    op.create_index(op.f('ix_problemas_id'), 'problemas', ['id'], unique=False)
    op.create_index(op.f('ix_problemas_nome'),
                    'problemas', ['nome'], unique=False)
    op.create_table('tags',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('nome', sa.String(length=32), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_nome'), 'tags', ['nome'], unique=False)
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(
                        length=32), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('password', sa.String(
                        length=64), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'),
                    'users', ['username'], unique=True)
    op.create_table('arquivos',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('nome', sa.String(length=64), nullable=False),
                    sa.Column('corpo', sa.String(
                        length=250000), nullable=False),
                    sa.Column('secao', sa.Enum('RECURSO', 'FONTE', 'ANEXO',
                                               'SOLUCAO', name='secaoschema'), nullable=True),
                    sa.Column('status', sa.String(), nullable=True),
                    sa.Column('problema_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['problema_id'], ['problemas.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_arquivos_id'), 'arquivos', ['id'], unique=False)
    op.create_index(op.f('ix_arquivos_nome'),
                    'arquivos', ['nome'], unique=False)
    op.create_index(op.f('ix_arquivos_secao'),
                    'arquivos', ['secao'], unique=False)
    op.create_index(op.f('ix_arquivos_status'),
                    'arquivos', ['status'], unique=False)
    op.create_table('declaracoes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('titulo', sa.String(length=64), nullable=False),
                    sa.Column('contextualizacao', sa.String(
                        length=10240), nullable=False),
                    sa.Column('formatacao_entrada', sa.String(
                        length=10240), nullable=False),
                    sa.Column('formatacao_saida', sa.String(
                        length=10240), nullable=False),
                    sa.Column('observacao', sa.String(
                        length=10240), nullable=True),
                    sa.Column('tutorial', sa.String(
                        length=80240), nullable=True),
                    sa.Column('problema_id', sa.Integer(), nullable=True),
                    sa.Column('idioma', sa.Enum('AF', 'AR', 'HY', 'AZ', 'BE', 'BN', 'BG', 'CA', 'ZH', 'HR', 'CS', 'DA', 'NL', 'EN', 'ET', 'TL', 'FI', 'FR', 'KA', 'DE', 'EL', 'HE', 'HI', 'HU', 'IS', 'ID', 'GA', 'JA', 'KK',
                                                'KO', 'KY', 'LT', 'MK', 'MS', 'MN', 'NO', 'FA', 'PL', 'PT', 'RO', 'RU', 'SR', 'SI', 'SK', 'SL', 'ES', 'SV', 'TG', 'TH', 'TR', 'TK', 'UK', 'UR', 'UZ', 'VI', 'OT', name='idiomaenum'), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['problema_id'], ['problemas.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_declaracoes_id'),
                    'declaracoes', ['id'], unique=False)
    op.create_index(op.f('ix_declaracoes_titulo'),
                    'declaracoes', ['titulo'], unique=False)
    op.create_table('problema_tag',
                    sa.Column('problema_id', sa.Integer(), nullable=True),
                    sa.Column('tag_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['problema_id'], ['problemas.id'], ),
                    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
                    )
    op.create_table('validadores',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('nome', sa.String(length=64), nullable=False),
                    sa.Column('corpo', sa.String(
                        length=250000), nullable=False),
                    sa.Column('linguagem', sa.String(), nullable=False),
                    sa.Column('problema_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['problema_id'], ['problemas.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('problema_id')
                    )
    op.create_index(op.f('ix_validadores_id'),
                    'validadores', ['id'], unique=False)
    op.create_index(op.f('ix_validadores_nome'),
                    'validadores', ['nome'], unique=False)
    op.create_table('verificadores',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('nome', sa.String(length=64), nullable=False),
                    sa.Column('corpo', sa.String(
                        length=250000), nullable=False),
                    sa.Column('linguagem', sa.String(), nullable=False),
                    sa.Column('problema_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['problema_id'], ['problemas.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('problema_id')
                    )
    op.create_index(op.f('ix_verificadores_id'),
                    'verificadores', ['id'], unique=False)
    op.create_index(op.f('ix_verificadores_nome'),
                    'verificadores', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verificadores_nome'), table_name='verificadores')
    op.drop_index(op.f('ix_verificadores_id'), table_name='verificadores')
    op.drop_table('verificadores')
    op.drop_index(op.f('ix_validadores_nome'), table_name='validadores')
    op.drop_index(op.f('ix_validadores_id'), table_name='validadores')
    op.drop_table('validadores')
    op.drop_table('problema_tag')
    op.drop_index(op.f('ix_declaracoes_titulo'), table_name='declaracoes')
    op.drop_index(op.f('ix_declaracoes_id'), table_name='declaracoes')
    op.drop_table('declaracoes')
    op.drop_index(op.f('ix_arquivos_status'), table_name='arquivos')
    op.drop_index(op.f('ix_arquivos_secao'), table_name='arquivos')
    op.drop_index(op.f('ix_arquivos_nome'), table_name='arquivos')
    op.drop_index(op.f('ix_arquivos_id'), table_name='arquivos')
    op.drop_table('arquivos')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_nome'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_problemas_nome'), table_name='problemas')
    op.drop_index(op.f('ix_problemas_id'), table_name='problemas')
    op.drop_table('problemas')
    # ### end Alembic commands ###
