"""Cria coluna linguagem em arquivo

Revision ID: 91faf626596d
Revises: 0b16dad5aa50
Create Date: 2024-03-06 19:37:10.481758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91faf626596d'
down_revision = '0b16dad5aa50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arquivos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linguagem', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arquivos', schema=None) as batch_op:
        batch_op.drop_column('linguagem')

    # ### end Alembic commands ###
