"""Adiciona coluna erro em resposta

Revision ID: 99afadda833c
Revises: 5bffb763397b
Create Date: 2024-03-09 11:58:10.184097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99afadda833c'
down_revision = '5bffb763397b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema_respostas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('erro', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema_respostas', schema=None) as batch_op:
        batch_op.drop_column('erro')

    # ### end Alembic commands ###
