"""Cria modelo ProblemaTeste e relaciona com problema

Revision ID: 99ccfb2338ff
Revises: 38e402437b8f
Create Date: 2024-02-09 00:00:00.228437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ccfb2338ff'
down_revision = '38e402437b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problema_testes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=64), nullable=False),
    sa.Column('tipo', sa.Enum('MANUAL', 'GERADO', name='tipotesteproblemaenum'), nullable=False),
    sa.Column('entrada', sa.String(length=250000), nullable=False),
    sa.Column('exemplo', sa.Boolean(), nullable=False),
    sa.Column('descricao', sa.String(length=250000), nullable=True),
    sa.Column('problema_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['problema_id'], ['problemas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('problema_testes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_problema_testes_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema_testes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_problema_testes_id'))

    op.drop_table('problema_testes')
    # ### end Alembic commands ###
