"""insere delete em cascata em validadorTeste ao excluir validador

Revision ID: 9e3dd516a737
Revises: 71a76b3153e7
Create Date: 2024-02-13 14:10:23.212759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e3dd516a737'
down_revision = '71a76b3153e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validador_testes', schema=None) as batch_op:
        batch_op.drop_constraint('validador_testes_validador_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('validador_testes_validador_id_fkey', 'validadores', ['validador_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validador_testes', schema=None) as batch_op:
        batch_op.drop_constraint('validador_testes_validador_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('validador_testes_validador_id_fkey', 'validadores', ['validador_id'], ['id'])

    # ### end Alembic commands ###
