"""cria tabela problemaResposta e relaciona com problema e user

Revision ID: abb9072e627d
Revises: e73c2b171054
Create Date: 2024-02-14 02:47:26.386162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abb9072e627d'
down_revision = 'e73c2b171054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problema_respostas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resposta', sa.String(length=250000), nullable=False),
    sa.Column('respondido_em', sa.DateTime(), nullable=True),
    sa.Column('tempo', sa.Integer(), nullable=False),
    sa.Column('memoria', sa.Integer(), nullable=False),
    sa.Column('linguagem', sa.String(), nullable=False),
    sa.Column('problema_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['problema_id'], ['problemas.id'], name='problema_respostas_problema_id_fkey'),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], name='problema_respostas_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('problema_respostas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_problema_respostas_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema_respostas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_problema_respostas_id'))

    op.drop_table('problema_respostas')
    # ### end Alembic commands ###
