"""inclui delete SET NULL entre resposta e user

Revision ID: b54012cc8c39
Revises: 2d302608bc4b
Create Date: 2024-03-30 14:28:57.014553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b54012cc8c39'
down_revision = '2d302608bc4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema_respostas', schema=None) as batch_op:
        batch_op.drop_constraint('problema_respostas_usuario_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('problema_respostas_usuario_id_fkey', 'users', ['usuario_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema_respostas', schema=None) as batch_op:
        batch_op.drop_constraint('problema_respostas_usuario_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('problema_respostas_usuario_id_fkey', 'users', ['usuario_id'], ['id'])

    # ### end Alembic commands ###
