"""torna coluna linguagens obrigatoria em problemas

Revision ID: c1056f22e3f7
Revises: dccadd90f1c7
Create Date: 2024-04-12 13:04:40.079219

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1056f22e3f7'
down_revision = 'dccadd90f1c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problemas', schema=None) as batch_op:
        batch_op.alter_column('linguagens',
                              existing_type=postgresql.ARRAY(sa.VARCHAR()),
                              nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problemas', schema=None) as batch_op:
        batch_op.alter_column('linguagens',
                              existing_type=postgresql.ARRAY(sa.VARCHAR()),
                              nullable=True)

    # ### end Alembic commands ###
