"""torna unica a coluna nome de problema

Revision ID: c11b14d87ece
Revises: 5729be25b9d2
Create Date: 2024-02-25 18:26:39.177417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c11b14d87ece'
down_revision = '5729be25b9d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problemas', schema=None) as batch_op:
        batch_op.drop_index('ix_problemas_nome')
        batch_op.create_index(batch_op.f('ix_problemas_nome'), ['nome'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problemas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_problemas_nome'))
        batch_op.create_index('ix_problemas_nome', ['nome'], unique=False)

    # ### end Alembic commands ###
