"""Adiciona coluna de saida em testes

Revision ID: d9affcc0a6fd
Revises: 6ee6e728c4df
Create Date: 2024-08-24 18:45:24.716884

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd9affcc0a6fd'
down_revision = '6ee6e728c4df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema_testes', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('saida', sa.String(length=1000000), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema_testes', schema=None) as batch_op:
        batch_op.drop_column('saida')

    # ### end Alembic commands ###
