"""cria coluna saida esperada em resposta

Revision ID: e457c69065c4
Revises: 29aa2b54b068
Create Date: 2024-03-07 21:26:03.568302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e457c69065c4'
down_revision = '29aa2b54b068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema_respostas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saida_esperada', sa.ARRAY(sa.String()), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problema_respostas', schema=None) as batch_op:
        batch_op.drop_column('saida_esperada')

    # ### end Alembic commands ###
