"""insere coluna criado_em em problema

Revision ID: e73c2b171054
Revises: 9e3dd516a737
Create Date: 2024-02-13 19:24:07.696817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e73c2b171054'
down_revision = '9e3dd516a737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problemas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_em', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('problemas', schema=None) as batch_op:
        batch_op.drop_column('criado_em')

    # ### end Alembic commands ###
