"""remove colunas do tipo Enum em modelos

Revision ID: eda77c342fdd
Revises: 99afadda833c
Create Date: 2024-03-14 22:36:58.137846

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eda77c342fdd'
down_revision = '99afadda833c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arquivos', schema=None) as batch_op:
        batch_op.alter_column('secao',
               existing_type=postgresql.ENUM('RECURSO', 'FONTE', 'ANEXO', 'SOLUCAO', name='secaoenum'),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('declaracoes', schema=None) as batch_op:
        batch_op.alter_column('idioma',
               existing_type=postgresql.ENUM('AF', 'AR', 'HY', 'AZ', 'BE', 'BN', 'BG', 'CA', 'ZH', 'HR', 'CS', 'DA', 'NL', 'EN', 'ET', 'TL', 'FI', 'FR', 'KA', 'DE', 'EL', 'HE', 'HI', 'HU', 'IS', 'ID', 'GA', 'JA', 'KK', 'KO', 'KY', 'LT', 'MK', 'MS', 'MN', 'NO', 'FA', 'PL', 'PT', 'RO', 'RU', 'SR', 'SI', 'SK', 'SL', 'ES', 'SV', 'TG', 'TH', 'TR', 'TK', 'UK', 'UR', 'UZ', 'VI', 'OT', name='idiomaenum'),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('problema_testes', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=postgresql.ENUM('MANUAL', 'GERADO', name='tipotesteproblemaenum'),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('validador_testes', schema=None) as batch_op:
        batch_op.alter_column('veredito',
               existing_type=postgresql.ENUM('VALID', 'INVALID', name='vereditovalidadortesteenum'),
               type_=sa.String(),
               existing_nullable=False)

    with op.batch_alter_table('verificador_testes', schema=None) as batch_op:
        batch_op.alter_column('veredito',
               existing_type=postgresql.ENUM('OK', 'WA', 'PE', 'CA', name='vereditoverificadortesteenum'),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verificador_testes', schema=None) as batch_op:
        batch_op.alter_column('veredito',
               existing_type=sa.String(),
               type_=postgresql.ENUM('OK', 'WA', 'PE', 'CA', name='vereditoverificadortesteenum'),
               existing_nullable=False)

    with op.batch_alter_table('validador_testes', schema=None) as batch_op:
        batch_op.alter_column('veredito',
               existing_type=sa.String(),
               type_=postgresql.ENUM('VALID', 'INVALID', name='vereditovalidadortesteenum'),
               existing_nullable=False)

    with op.batch_alter_table('problema_testes', schema=None) as batch_op:
        batch_op.alter_column('tipo',
               existing_type=sa.String(),
               type_=postgresql.ENUM('MANUAL', 'GERADO', name='tipotesteproblemaenum'),
               existing_nullable=False)

    with op.batch_alter_table('declaracoes', schema=None) as batch_op:
        batch_op.alter_column('idioma',
               existing_type=sa.String(),
               type_=postgresql.ENUM('AF', 'AR', 'HY', 'AZ', 'BE', 'BN', 'BG', 'CA', 'ZH', 'HR', 'CS', 'DA', 'NL', 'EN', 'ET', 'TL', 'FI', 'FR', 'KA', 'DE', 'EL', 'HE', 'HI', 'HU', 'IS', 'ID', 'GA', 'JA', 'KK', 'KO', 'KY', 'LT', 'MK', 'MS', 'MN', 'NO', 'FA', 'PL', 'PT', 'RO', 'RU', 'SR', 'SI', 'SK', 'SL', 'ES', 'SV', 'TG', 'TH', 'TR', 'TK', 'UK', 'UR', 'UZ', 'VI', 'OT', name='idiomaenum'),
               existing_nullable=False)

    with op.batch_alter_table('arquivos', schema=None) as batch_op:
        batch_op.alter_column('secao',
               existing_type=sa.String(),
               type_=postgresql.ENUM('RECURSO', 'FONTE', 'ANEXO', 'SOLUCAO', name='secaoenum'),
               existing_nullable=True)

    # ### end Alembic commands ###
