"""altera tipo da coluna numero na tabela ValidadorTeste

Revision ID: f5512a600333
Revises: 429c3e3bbdba
Create Date: 2024-02-09 01:19:05.299549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5512a600333'
down_revision = '429c3e3bbdba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validador_testes', schema=None) as batch_op:
        batch_op.alter_column('numero',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validador_testes', schema=None) as batch_op:
        batch_op.alter_column('numero',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###
